/* Generate dist/sw.js after `vite build`: an app-shell service worker
 * (PWA/offline). Normal assets -- including public/synth/ -- are
 * precached. The MPEG-2 playback decoder and large movie converter are fetched
 * and cached independently, only when the user first prepares or converts a
 * movie. No runtime deps, mirroring the app (a build-time script instead of
 * vite-plugin-pwa). */

import { createHash } from "node:crypto";
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join, relative } from "node:path";

const dist = new URL("../dist/", import.meta.url).pathname;

const files = [];
(function walk(dir) {
    for (const e of readdirSync(dir, { withFileTypes: true })) {
        const p = join(dir, e.name);
        if (e.isDirectory()) walk(p);
        else files.push(relative(dist, p));
    }
})(dist);
files.sort();
const lazyAsset = /^(?:libav\/|assets\/(?:ffmpeg-core|movie-converter|movie-decoder\.worker|worker)-)/;

const hash = createHash("sha256");
const urls = [];
for (const f of files) {
    if (f === "sw.js" || f === ".vite/manifest.json" || f.endsWith(".md"))
        continue;
    hash.update(f);
    hash.update(readFileSync(join(dist, f)));
    if (lazyAsset.test(f.split("\\").join("/"))) continue;
    /* the app shell is cached under its navigation URL "./" */
    urls.push(f === "index.html" ? "./" : "./" + f.split("\\").join("/"));
}
const version = hash.digest("hex").slice(0, 16);

/* Cache names carry a build timestamp so activate can ORDER them: the
 * previous generation is kept alive because a page served by the outgoing
 * worker may still be loading its (old-hash) subresources when the new
 * worker activates mid-navigation -- deleting every old cache there breaks
 * that page hard when offline (hit in testing, 2026-07-18). One spare
 * generation (~1 MB) closes the race; older ones are dropped. */
const sw = `/* generated by scripts/gen-sw.mjs -- do not edit */
const CACHE = "ae3-player-${Date.now()}-${version}";
const ASSETS = ${JSON.stringify(urls, null, 1)};
const LAZY_ASSET = ${lazyAsset};

self.addEventListener("install", (e) => {
    e.waitUntil((async () => {
        const cache = await caches.open(CACHE);
        await cache.addAll(ASSETS.map((u) => new Request(u, { cache: "reload" })));
        await self.skipWaiting();
    })());
});

self.addEventListener("activate", (e) => {
    e.waitUntil((async () => {
        const gen = (k) => Number(k.split("-")[2]) || 0;
        const old = (await caches.keys())
            .filter((k) => k.startsWith("ae3-player-") && k !== CACHE)
            .sort((a, b) => gen(b) - gen(a));
        for (const k of old.slice(1)) await caches.delete(k);
        await self.clients.claim();
    })());
});

/* cache-first for everything in scope; navigations get the app shell. A miss
 * checks the other generations (mixed-generation pages during an update),
 * then the network. ignoreVary is required: dev/preview servers stamp assets
 * with "Vary: Origin", and a subresource load (no-cors style/script) then
 * refuses to match the install-time cache entry -- offline page loads break
 * while page-JS fetches work (hit in testing, 2026-07-18). The cache is
 * fully versioned by content, so URL identity is the correct key. */
const OPTS = { ignoreSearch: true, ignoreVary: true };
self.addEventListener("fetch", (e) => {
    const req = e.request;
    if (req.method !== "GET" || !req.url.startsWith(self.registration.scope))
        return;
    e.respondWith((async () => {
        const key = req.mode === "navigate" ? "./" : req;
        let cache;
        try {
            cache = await caches.open(CACHE);
            const cached = await cache.match(key, OPTS) ?? await caches.match(key, OPTS);
            if (cached) return cached;
        } catch (error) {
            console.error("service-worker cache lookup failed", error);
        }
        const response = await fetch(req);
        const scopePath = new URL(self.registration.scope).pathname;
        const requestPath = new URL(req.url).pathname.slice(scopePath.length);
        if (response.ok && cache && LAZY_ASSET.test(requestPath)) {
            try {
                await cache.put(req, response.clone());
            } catch (error) {
                console.error("service-worker lazy cache write failed", error);
            }
        }
        return response;
    })());
});
`;

writeFileSync(join(dist, "sw.js"), sw);
console.log(`dist/sw.js: ${urls.length} assets precached, version ${version}`);
